apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deploy
  name: my-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: my-deploy
    spec:
      containers:
      - image: registry.digitalocean.com/busybox
        name: busybox
        resources: {}
        command:
        - 'sh'
        - '-c'
        - 'sleep 30'
