apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    not-app: my-deploy
  name: my-deploy-wrong
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      not-app: my-deploy
  strategy: {}
  template:
    metadata:
      labels:
        not-app: my-deploy
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
        command:
        - 'sh'
        - '-c'
        - 'sleep 30'
