apiVersion: v1
kind: Pod
metadata:
  name: docr-busybox
  namespace: default
spec:
  containers:
  - image: registry.digitalocean.com/busybox:latest
    imagePullPolicy: Always
    name: busybox
    resources: {}
    command:
    - 'sh'
    - '-c'
    - 'sleep 30'
