apiVersion: v1
kind: Pod
metadata:
  name: docr-busybox
  namespace: default
spec:
  imagePullSecrets:
  - name: do-sfo3-k8s-1-21-5-do-cezar-bernardi
  containers:
  - image: registry.digitalocean.com/do-sfo3-k8s-1-21-5-do-cezar-bernardi/busybox:latest
    imagePullPolicy: Always
    name: busybox
    resources: {}
    command:
    - 'sh'
    - '-c'
    - 'sleep 30'
