apiVersion: v1
kind: Pod
metadata:
  name: gcr-busybox
  namespace: default
spec:
  containers:
  - image: gcr.io/google-containers/busybox:latest
    imagePullPolicy: Always
    name: busybox
    resources: {}
    command:
    - 'sh'
    - '-c'
    - 'sleep 30'
