apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-deployment-labels
  annotations:
    policies.kyverno.io/title: Require Labels
    policies.kyverno.io/subject: Deployment
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: check-for-labels
    match:
      resources:
        kinds:
        - Deployment
    validate:
      message: "The label `app` is required."
      pattern:
        metadata:
          labels:
            app: "?*"
